import { getYearRows,getYearSettings,saveYearSettings,addScheduleRow,listRequests,updateRequest,createBackup,writeAudit } from "../firebase/data.js";
import { watchAuth,logout,changePassword } from "../firebase/auth.js";
const $=s=>document.querySelector(s); let rows=[],settings={};
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3000)};
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function conflictRows(a){const out=[];for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const x=a[i],y=a[j];if(x.day!==y.day||!x.timeFrom||!y.timeFrom)continue;const overlap=Number(x.timeFrom)<Number(y.timeTo)&&Number(y.timeFrom)<Number(x.timeTo);if(!overlap)continue;let type="";if(x.room&&x.room===y.room)type="تعارض القاعة";else if(x.teacher&&x.teacher===y.teacher)type="تعارض المدرس";else if(x.group&&x.group===y.group&&x.major===y.major)type="تعارض المجموعة";if(type)out.push({x,y,type})}return out}
function render(){
 $("#count-records").textContent=rows.length;$("#count-materials").textContent=new Set(rows.map(x=>x.course).filter(Boolean)).size;$("#count-rooms").textContent=new Set(rows.map(x=>x.room).filter(Boolean)).size;$("#count-majors").textContent=new Set(rows.map(x=>x.major).filter(Boolean)).size;
 const cs=conflictRows(rows);$("#count-conflicts").textContent=cs.length;
 $("#records-body").innerHTML=rows.slice(0,100).map(r=>`<tr><td>${esc(r.course)}</td><td>${esc(r.major)}</td><td>${esc(r.level)}</td><td>${esc(r.day)}</td><td>${esc(r.teacher)}</td><td>${esc(r.room)}</td></tr>`).join("");
 $("#conflicts-list").innerHTML=cs.map(c=>`<div class="result"><b>${esc(c.type)}</b><span>${esc(c.x.course)} ↔ ${esc(c.y.course)} | ${esc(c.x.day)} ${esc(c.x.timeFrom)}-${esc(c.x.timeTo)} | ${esc(c.x.room)}</span></div>`).join("")||"<div class='empty'>لا توجد تعارضات مكتشفة.</div>";
 const bad=rows.filter(r=>!r.college||!r.major||!r.level||!r.course||!r.day||r.timeFrom==null||r.timeTo==null||!r.room);$("#review-list").innerHTML=bad.map(r=>`<div class="result"><b>${esc(r.course||"سجل ناقص")}</b><span>السجل يحتاج مراجعة: ${["college","major","level","day","timeFrom","timeTo","room"].filter(k=>r[k]==null||r[k]==="").join("، ")}</span></div>`).join("")||"<div class='empty'>لا توجد سجلات ناقصة في البيانات المحملة.</div>";
}
async function load(){
 try{settings=await getYearSettings();$("#active-year").innerHTML=(settings.years||[]).map(y=>`<option>${esc(y)}</option>`).join("");$("#active-year").value=settings.activeYear;rows=await getYearRows(settings.activeYear);render();await loadRequests();}catch(e){console.error(e);toast("تعذر الاتصال بـFirebase")}
}
async function loadRequests(){try{const rs=await listRequests();$("#count-requests").textContent=rs.filter(r=>r.status==="جديد").length;$("#requests-body").innerHTML=rs.map(r=>`<tr><td>${esc(r.id)}</td><td>${esc(r.studentId)}</td><td>${esc(r.type)}</td><td>${esc(r.major)}</td><td>${esc(r.title)}</td><td><select data-status="${esc(r.id)}"><option ${r.status==="جديد"?"selected":""}>جديد</option><option ${r.status==="قيد المراجعة"?"selected":""}>قيد المراجعة</option><option ${r.status==="تم الحل"?"selected":""}>تم الحل</option><option ${r.status==="مرفوض"?"selected":""}>مرفوض</option></select></td><td><button class="small" data-save-request="${esc(r.id)}">حفظ</button></td></tr>`).join("")}catch(e){console.error(e);toast("تعذر تحميل الطلبات")}}
$("#save-year").onclick=async()=>{try{let y=$("#active-year").value;const n=$("#new-year").value.trim();if(n&&!settings.years.includes(n)){settings.years.push(n);y=n}settings.activeYear=y;settings.semesters=settings.semesters||{};settings.semesters[y]=$("#semester").value;await saveYearSettings(settings);rows=await getYearRows(y);render();toast("تم حفظ إعداد السنة")}catch(e){toast("تعذر حفظ إعداد السنة")}};
$("#material-form").onsubmit=async e=>{e.preventDefault();const row={college:$("#m-college").value,major:$("#m-major").value,level:$("#m-level").value,course:$("#m-course").value,type:$("#m-type").value,day:$("#m-day").value,teacher:$("#m-teacher").value,timeFrom:Number($("#m-from").value),timeTo:Number($("#m-to").value),room:$("#m-room").value,year:settings.activeYear};try{await addScheduleRow(row);rows=await getYearRows(settings.activeYear);render();e.target.reset();await writeAudit("Add",row.course,{year:settings.activeYear});toast("تم حفظ السجل")}catch(e){console.error(e);toast("تعذر الحفظ")}};
$("#requests-body").addEventListener("click",async e=>{const b=e.target.closest("[data-save-request]");if(!b)return;const id=b.dataset.saveRequest,sel=document.querySelector(`[data-status="${CSS.escape(id)}"]`);try{await updateRequest(id,{status:sel.value});await writeAudit("Request changes",`تحديث ${id}`,{status:sel.value});toast("تم تحديث الطلب")}catch(e){toast("تعذر تحديث الطلب")}});
$("#refresh-requests").onclick=loadRequests;$("#logout").onclick=async()=>{await logout();location.href="index.html"};$("#password-form").onsubmit=async e=>{e.preventDefault();if($("#new-password").value!==$("#confirm-password").value){toast("تأكيد كلمة المرور غير مطابق");return}try{await changePassword($("#current-password").value,$("#new-password").value);toast("تم تغيير كلمة المرور")}catch(e){toast("تعذر تغيير كلمة المرور: "+(e.code||"خطأ"))}};
$("#backup-btn").onclick=async()=>{try{await createBackup(settings.activeYear,rows,"نسخة يدوية من لوحة الإدارة");await writeAudit("Backup",`نسخة ${settings.activeYear}`,{});toast("تم إنشاء النسخة الاحتياطية")}catch(e){toast("تعذر إنشاء النسخة")}};
$("#side-toggle").onclick=()=>$("#sidebar").classList.toggle("collapsed");
watchAuth(u=>{if(!u){location.href="index.html";return}load()});
